# Site settings
title: Imran Shahid
twitter_username: ishahid
name: Imran Shahid

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/ishahid
 - title: StackOverflow
   url: https://stackoverflow.com/users/393564/imran-s
 - title: LinkedIn
   url: https://au.linkedin.com/in/ishahid

#Any buzzword skills you want to include
skills:
 - Python
 - Django
 - SQL
 - REST
 - Tech Architecture
 - AWS

#Work experience is required
roles:
 - title: Head Architect
   start: 2014
   end: Ongoing
   employer: Xref Pty Ltd

#Education is required
education:
 - level: MCS, Computer Science
   date: 2004
   subject: Computer Science
   school: University of Arid Agriculture, Rawalpindi
 - level: BCS, Computer Science
   date: 2001
   subject: Computer Science
   school: University of The Punjab

#List of interesting Github repo/projects to include - optional
github:
